backend/Dockerfile, backend/README.md, backend/docker-compose.dev.yml, backend/graphql/schema/generated/nexus-typegen.ts, backend/graphql/schema/generated/schema.graphql, backend/graphql/schema/schema.ts, backend/package-lock.json, backend/package.json, backend/prisma/migrations/20210804140645_added_project_dates/migration.sql, backend/prisma/schema.prisma, frontend/hooks/useProjects.ts, frontend/pages/projects.tsx, frontend/pages/projects/[id].tsx
i have changed the look of the "undefined Date" message with a ternary operator
=> if the dates are undefined it is more userfriendly

.github/workflows/node.js.yml, frontend/pages/time.tsx
=> ci: fix github actions

app/backend/graphql/generated/nexus-typegen.ts, app/backend/graphql/generated/schema.graphql, app/backend/graphql/project/mutations/index.ts, app/backend/graphql/project/mutations/isUserAdminMember.ts, app/backend/graphql/project/mutations/projectCreateMutationField.ts, app/backend/graphql/project/mutations/projectDeleteMutationField.ts, app/backend/graphql/project/mutations/projectUpdateMutationField.ts, app/backend/graphql/project/projectInput.ts, app/backend/graphql/schema.ts, app/frontend/generated/graphql.ts
First part of #31
~⚠️ This is PR is based on #61. Only merge when #61 has been merged.~
=> feat(graphql): add projectCreate, projectUpdate and projectDelete mutations

app/postcss.config.js, app/tailwind.config.js
Enable JIT Mode in Tailwind: https://tailwindcss.com/docs/just-in-time-mode
- faster build
- allows all tailwind variants out of the box
=> build(tailwind): use Just-In-Time mode

app/frontend/components/button/button.tsx, app/frontend/components/projectForm/projectForm.tsx
=> add Button component

app/backend/graphql/project/mutations/projectCreateMutationField.ts, app/backend/graphql/project/mutations/projectDeleteMutationField.ts, app/backend/graphql/project/mutations/projectUpdateMutationField.ts, app/backend/graphql/project/queries/projectQueryField.ts, app/backend/graphql/project/queries/projectsQueryField.ts, app/backend/graphql/task/mutations/taskDeleteMutationField.ts, app/backend/graphql/workHour/mutations/createWorkHourMutationField.ts, app/package-lock.json, app/package.json
Changes:
- update to next v12
- remove circular dependencies (this breaks on v12)
=> chore: update to next v12

app/backend/graphql/context.ts
source: https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices
=> fix(prisma): fix to many db connection on dev

app/frontend/components/button/button.tsx, app/frontend/components/deleteProjectModal.tsx, app/frontend/components/projectForm/projectForm.tsx
Maybe a slim variant of danger will be needed later too?
=> Rename redButton to danger and create variant: dangerSlim

app/frontend/components/projectForm/projectForm.tsx, app/frontend/styles/globals.css, app/package-lock.json, app/package.json, app/tailwind.config.js
HTML form elements may look different in each browser.
This plugin resets these styles and apply some basic CSS to them.
Introduction video: https://youtu.be/pONeWAzDsQg
=> feat(tailwind): add tailwind forms plugin

app/frontend/components/inputField/inputField.tsx, app/frontend/components/projectForm/projectForm.tsx, app/frontend/components/taskList/taskList.tsx
=> Add inputField component

app/pages/projects/[id].tsx
for more info: https://formidable.com/open-source/urql/docs/basics/document-caching/#adding-typenames
fix #93
=> fix(project details): adding first task does not update the task list

app/frontend/components/inputField/inputField.tsx
Delete black border from inputField component
=> fix inputField tailwindcss

.github/workflows/node.js.yml, app/.ci/check-graphql-generator.js, app/package-lock.json, app/package.json
I noticed that sometimes we forget to use the GraphQL generator. This job checks that.
=> ci(github actions): add job to check if graphql generator has been run

app/codegen.yml, app/frontend/generated/graphql.ts, app/pages/[teamSlug]/team/invite/[inviteKey].tsx, app/pages/[teamSlug]/team/invite/teamAcceptInvite.graphql
=> add inviteAcceptPage

app/frontend/components/bookWorkHourModal.tsx, app/frontend/components/button/button.tsx, app/frontend/createWorkHour.graphql, app/frontend/generated/graphql.ts, app/frontend/projects.graphql, app/package-lock.json, app/package.json, app/pages/time.tsx
Closes #44 
I added the "comment" but I couldn't be able to see it on Prisma studio.
I think, we would of course still need to implement some validation on the inputs.
=> Book Work Hours into Tasks

app/frontend/generated/graphql.ts, app/frontend/team.graphql, app/pages/[teamSlug]/team/index.tsx, app/pages/_app.tsx
=> refactor: use team api routes for team page

app/backend/graphql/generated/nexus-typegen.ts, app/backend/graphql/generated/schema.graphql, app/backend/graphql/project/project.ts, app/backend/graphql/schema.ts, app/backend/graphql/task/index.ts, app/backend/graphql/task/mutations/index.ts, app/backend/graphql/task/mutations/taskArchiveMutationField.ts, app/backend/graphql/task/task.ts, app/backend/prisma/migrations/20220114081417_add_archived_at_to_task/migration.sql, app/backend/prisma/schema.prisma, app/frontend/components/deleteTaskModal.tsx, app/frontend/generated/graphql.ts, app/frontend/project.graphql, app/frontend/taskArchive.graphql, app/frontend/taskDelete.graphql
=> Added archive or delete tasks

app/pages/[teamSlug]/customers/index.tsx, app/pages/[teamSlug]/team/index.tsx, app/pages/team.tsx
=> Add Protected Page to Team Pages

app/frontend/components/taskForm/taskForm.tsx, app/frontend/components/taskList/taskList.tsx, app/frontend/generated/graphql.ts, app/frontend/project.graphql, app/frontend/taskUpdate.graphql, app/pages/[teamSlug]/tasks/[taskId].tsx, app/pages/[teamSlug]/tasks/task.graphql, app/pages/tasks.tsx
=> Task update

app/.eslintrc.js, app/frontend/components/projectTable.tsx, app/frontend/components/table/table.tsx, app/frontend/components/taskList/taskList.tsx, app/frontend/styles/globals.css, package-lock.json
=> Feature: custom table component

app/frontend/components/bookWorkHourModal.tsx, app/frontend/components/calendarIcon.tsx, app/frontend/components/calendarSelector.tsx, app/frontend/components/hourInput.tsx, app/frontend/components/modal.tsx, app/frontend/components/projectForm/projectForm.tsx, app/frontend/components/projectTable.tsx, app/frontend/components/taskForm/taskForm.tsx, app/frontend/components/topNavigation/topNavigation.tsx, app/frontend/components/weekSelector.tsx, app/frontend/styles/globals.css, app/package-lock.json, app/package.json, app/pages/[teamSlug]/customers/add.tsx, app/pages/[teamSlug]/team/invite/[inviteKey].tsx, app/pages/_app.tsx, app/pages/time.tsx
=> refactor(prettier): add tailwind prettier plugin

app/backend/graphql/generated/nexus-typegen.ts, app/backend/graphql/generated/schema.graphql, app/backend/graphql/project/mutations/projectDeleteMutationField.ts, app/backend/graphql/project/mutations/projectUpdateMutationField.ts, app/backend/graphql/project/queries/projectQueryField.ts, app/backend/graphql/task/taskInput.ts, app/backend/prisma/migrations/20220201084522_project_id_updated_from_int_to_string/migration.sql, app/backend/prisma/schema.prisma, app/frontend/components/hourInput.tsx, app/frontend/components/taskForm/taskForm.tsx, app/frontend/components/taskList/taskList.tsx, app/frontend/generated/graphql.ts
=> Updated projectId type from Int to string

app/pages/[teamSlug]/team/index.page.tsx
=> Team form updates when moving between teams

app/backend/graphql/generated/nexus-typegen.ts, app/backend/graphql/generated/schema.graphql, app/backend/graphql/user/user.ts, app/frontend/generated/graphql.ts, app/frontend/team.graphql, app/pages/[teamSlug]/team/index.page.tsx
=> User projects list

.github/workflows/node.js.yml, app/backend/getTestServer.ts, app/backend/graphql/schema.ts, app/backend/graphql/team/queries/teamQueryField.test.ts, app/backend/prisma/prismaJestEnvironment.js, app/jest.config.js, app/package-lock.json, app/package.json
=> test: add backend integration tests

app/jest.config.js
=> chore(jest): different colors for project display names

app/frontend/generated/graphql.ts, app/frontend/workHourDelete.graphql
=> Fixed deleting a work hour entry

app/backend/graphql/project/mutations/projectCreateMutationField.ts, app/backend/graphql/project/project.ts, app/backend/graphql/project/queries/projectQueryField.ts, app/backend/graphql/project/queries/projectsQueryField.ts, app/backend/graphql/report/queries/reportQueryField.ts, app/backend/graphql/task/queries/taskQueryField.ts, app/backend/graphql/user/user.ts, app/backend/prisma/migrations/20220401131729_use_user_id_in_project_membership_table/migration.sql, app/backend/prisma/schema.prisma, app/backend/prisma/seed.ts
=> refactor(backend): use user id in project membership table

app/frontend/components/bookWorkHourModal.tsx, app/frontend/components/customerForm/customerForm.tsx, app/frontend/components/projectForm/projectForm.tsx, app/frontend/components/taskDetailsModal.tsx, app/frontend/components/taskList/taskList.spec.tsx, app/frontend/components/taskList/taskList.tsx, app/frontend/components/teamForm/teamForm.test.tsx, app/frontend/components/teamForm/teamForm.tsx, app/package-lock.json, app/package.json
fixes #316 
fixes #305 
improves #296
=> feat(frontend): add yup validation to all forms

app/backend/graphql/workHour/mutations/workHourCreateMutationField.test.ts, app/backend/graphql/workHour/mutations/workHourCreateMutationField.ts
=> feat: workHourCreateMutationField authorize

app/frontend/components/hourInput.tsx
=> feat(frontend): focus hourInput

app/frontend/components/button/button.tsx, app/frontend/generated/graphql.ts, app/pages/[teamSlug]/team/[userId].page.tsx, app/pages/[teamSlug]/team/index.page.tsx, app/pages/[teamSlug]/team/user.graphql
- if you now click on a user (userID) in the member table, you will be redirected to a userDetailsPage  "draft"
=> feat: UserDetailsPage created and linked to member table

app/backend/graphql/team/mutations/teamCreateMutationField.test.ts, app/backend/graphql/team/mutations/teamCreateMutationField.ts
=> fix: team create restrictions

app/backend/graphql/team/mutations/teamUpdateMutationField.test.ts, app/backend/graphql/team/mutations/teamUpdateMutationField.ts
Co-authored-by: Yohannes Tesfay <YohannesTesfay@users.noreply.github.com>
=> 332 is Admin for Update Team

app/backend/graphql/project/queries/projectQueryField.ts
=> fix: Allow admins to load every project (projectQueryField)

app/frontend/components/bookWorkHourModal.test.tsx, app/frontend/components/bookWorkHourModal.tsx, app/frontend/components/hourInput.tsx, app/frontend/components/taskList/taskList.tsx, app/pages/[teamSlug]/time/index.page.tsx, app/pages/time.page.tsx
=> feat: direct task creation from work hour

app/frontend/components/bookWorkHourModal.tsx, app/frontend/components/button/button.tsx, app/frontend/components/hourInput.tsx, app/frontend/components/modal.tsx
=> style: book work hour modal styles

app/frontend/components/dayWeekSwitchButton.tsx, app/pages/time/index.page.tsx, app/pages/time/week.page.tsx
=> feat: create switch button for day/week, time.page.tsx -> index.page.tsx

app/frontend/components/dayWeekSwitchButton.tsx, app/pages/time/day.page.tsx, app/pages/time/index.page.tsx
everything works, but the design of the button needs to be revised
=> feat : create weekSwitcher and correct day/week chaos

app/frontend/components/projectForm/customerInput.tsx
=> fix: customer create bug

app/backend/graphql/generated/nexus-typegen.ts, app/backend/graphql/generated/schema.graphql, app/backend/graphql/workHour/mutations/workHourCreateMutationField.test.ts, app/backend/graphql/workHour/mutations/workHourCreateMutationField.ts, app/backend/graphql/workHour/mutations/workHourUpdateMutationField.test.ts, app/backend/graphql/workHour/workHour.ts, app/backend/graphql/workHour/workHourInput.ts, app/backend/prisma/migrations/20220826141517_remove_comment_field_from_work_hour/migration.sql, app/backend/prisma/schema.prisma, app/frontend/components/bookWorkHourModal.tsx, app/frontend/components/reportForm/reportForm.tsx, app/frontend/generated/graphql.ts, app/frontend/mocks/testData.ts, app/frontend/workHours.graphql, app/pages/[teamSlug]/reports/report.graphql, app/pages/[teamSlug]/time/index.page.tsx, app/pages/[teamSlug]/time/index.test.tsx
=> feat: remove comment from work hour (db, backend & frontend)

app/backend/graphql/workHour/mutations/workHourCreateMutationField.test.ts, app/backend/graphql/workHour/mutations/workHourCreateMutationField.ts, app/backend/prisma/migrations/20220902151808_workhours_unique_day/migration.sql, app/backend/prisma/prismaJestEnvironment.js, app/backend/prisma/schema.prisma
=> feat: added unique constraint & logic to mutation

app/pages/[teamSlug]/projects/[id].page.tsx, app/pages/[teamSlug]/projects/new.page.tsx
=> fix: fixed display errors edit

app/frontend/components/combobox/combobox.tsx
=> fix: selector overlap

app/frontend/components/teamForm/teamForm.tsx, app/pages/teams/new.page.tsx
=> feat: added responsive design to team form

.github/workflows/node.js.yml
=> ci(github-actions): fix deployment on prod

app/jest.config.js
=> chore: add collectCoverageFrom to jest config

app/frontend/components/weekPageTable.tsx
=> fix: add additionalTypenames to week view urql query

app/frontend/components/teamForm/teamForm.tsx
=> fix: add router to dismiss button and remove from team details

apps/web/pages/_app.page.tsx
=> feat: add container to all pages

apps/web/frontend/components/taskList/taskCell.tsx, apps/web/tailwind.config.js, packages/ui/inputField.tsx, packages/ui/package.json, pnpm-lock.yaml
https://user-images.githubusercontent.com/1886867/203345800-57bda9e3-8b31-4467-89f6-a3e3abf36084.mp4
=> feat(frontend): add loading spinner to InputField component

apps/web/frontend/components/customerForm/customerTable.tsx, apps/web/frontend/components/projectForm/projectForm.tsx, apps/web/pages/[teamSlug]/team/index.page.tsx
fix annoying react warning comments:
=> fix(frontend): clean react warning messages

.github/workflows/node.js.yml, Dockerfile, packages/pulumi/index.ts
fixes #571 
The environment variable `NEXTAUTH_URL` is needed during the docker build step.
=> ci: fix SSR on prod

apps/web/pages/[teamSlug]/team/[userId].page.tsx
=> fix: hide demote button for users own profile

apps/web/frontend/components/bookWorkHourModal.tsx, apps/web/frontend/components/hourInput.tsx
=> fix: fixed updates on blur hour input

apps/web-e2e/package.json, pnpm-lock.yaml
I updated playwright and everything works now for me 😅
=> fix(e2e-tests): fix playwright

apps/web/frontend/components/weekSelector.tsx, apps/web/pages/time/[day].page.tsx, apps/web/pages/time/index.page.test.tsx, apps/web/pages/time/index.page.tsx
close #602 
I also rewrote the logic of the week selector, because it showed wrong calendar weeks.
=> feat(time page): hold day of the week in URL

packages/backend/package.json, pnpm-lock.yaml
=> chore(backend): fix TypeScript errors on pothos types by upgrading to the latest pothos versions

apps/web/frontend/components/projectMemberList.tsx, apps/web/frontend/generated/graphql.ts, apps/web/frontend/project.graphql, apps/web/pages/projects/[id].page.tsx
=> feat(Project Page): display project members

apps/web-e2e/src/projectPage.spec.ts, apps/web/frontend/components/combobox/combobox.tsx, apps/web/frontend/generated/graphql.ts, apps/web/pages/projects/index.page.tsx, apps/web/pages/projects/projectCounts.graphql, packages/backend/src/graphql/generated/schema.graphql, packages/backend/src/graphql/project/queries/getWhereFormProjectFilter.ts, packages/backend/src/graphql/project/queries/index.ts, packages/backend/src/graphql/project/queries/projectsCountQueryField.ts, packages/backend/src/graphql/project/queries/projectsQueryField.ts, turbo.json
=> feat(Projects Page): add filter for project status (all/active/past/future)

apps/web/frontend/components/topNavigation/topNavigation.tsx, apps/web/frontend/components/topNavigation/topNavigationLink.tsx, apps/web/pages/sheet.page.tsx, apps/web/pages/time/sheet.page.tsx
=> Move sheet page from /time/sheet to /sheet

apps/web/frontend/components/reportForm/reportForm.tsx, apps/web/frontend/components/timebookPage.tsx, apps/web/frontend/components/topNavigation/topNavigationLink.tsx, apps/web/pages/_app.page.tsx
=> feat: adds print option to report page

.github/workflows/node.js.yml
=> ci: fix e2e-test pipeline

apps/web/frontend/components/topNavigation/topNavigation.tsx
=> Dark mode fix for tracking

apps/web/frontend/components/reportForm/reportForm.tsx
=> fix: empty report gets refreshed

apps/web/frontend/components/projectForm/projectForm.tsx, apps/web/frontend/components/taskList/taskList.tsx, packages/ui/src/inputField/inputField.tsx
=> Set the edit project font to black.

apps/web/frontend/components/projectMemberList.tsx
=> Fix <TableCell> dark mode

apps/web/frontend/assets/backIcon.svg, apps/web/frontend/assets/calendarIcon.svg, apps/web/frontend/assets/forwardIcon.svg, apps/web/frontend/assets/home.svg, apps/web/frontend/components/calendarIcon.tsx, apps/web/frontend/components/calendarSelector.spec.tsx, apps/web/frontend/components/calendarSelector.tsx, apps/web/frontend/components/projectForm/projectForm.tsx
=> fix: calendar selector opens on selected month

apps/web/frontend/components/calendarSelector.tsx, apps/web/frontend/components/pageHeading.tsx, apps/web/frontend/components/projectForm/projectForm.tsx, apps/web/frontend/components/projectMemberList/projectMemberList.tsx, apps/web/frontend/components/reportForm/reportForm.tsx, apps/web/frontend/components/timeSheetView/workHoursSheet.tsx, apps/web/pages/home.page.tsx, apps/web/pages/projects/index.page.tsx, apps/web/pages/sheet.page.tsx, apps/web/pages/week/index.page.tsx
=> Replaces the `h2` tags with the `PageHeading` component.

apps/web/frontend/components/addProjectMemberForm.tsx, apps/web/frontend/components/projectMemberList/projectMemberList.tsx, apps/web/frontend/generated/gql/gql.ts, apps/web/frontend/generated/gql/graphql.ts, apps/web/frontend/mocks/mocks.generated.ts, packages/backend/package.json, packages/backend/src/graphql/builder.ts, packages/backend/src/graphql/generated/schema.graphql, packages/backend/src/graphql/projectMembership/mutations/projectMembershipInviteByEmailMutationField.test.ts, packages/backend/src/graphql/projectMembership/mutations/projectMembershipInviteByEmailMutationField.ts, packages/ui/src/inputField/inputField.tsx, pnpm-lock.yaml
=> feat: mailto invitation link popup on project page

apps/web/frontend/components/weekTable/weekTableProjectRowGroup.tsx
=> feat: removes word break, removes task information, icons always on the left

apps/web/frontend/components/taskList/taskList.tsx, apps/web/frontend/components/taskList/taskRow.tsx
=> Adds Hide lock switch on task list if user is member

apps/web/frontend/components/reportForm/reportForm.test.tsx, apps/web/frontend/components/reportForm/reportForm.tsx, apps/web/frontend/components/reportForm/reportUserSelect.tsx, apps/web/pages/reports/[year-month]/[projectId].page.tsx, apps/web/pages/reports/[year-month]/index.page.tsx, apps/web/pages/reports/index.page.tsx
=> draft: changes reports page url to include date and project id

apps/web/frontend/components/reportForm/reportForm.tsx
=> feat: add report for all users

packages/backend/src/graphql/report/report.ts
=> feat: removes reports with 0 duration from report page

apps/web/frontend/components/addProjectMemberForm.tsx
=> fix addProjectMember button

Dockerfile, apps/web/next.config.js, apps/web/package.json, pnpm-lock.yaml
=> feat(app): use nextjs standlone mode

apps/web/frontend/components/trackingButtons/trackingButtons.tsx
Resolves #812 
Creates a flexbox div around two tracking buttons, lining them up horizontally
=> Align tracking buttons using flexbox

apps/web/frontend/components/trackingButtons/trackingButtons.tsx
closes: https://github.com/progwise/timebook/issues/820
=> fix: cancel tracking modal readability in light mode

apps/web/frontend/generated/gql/gql.ts, apps/web/frontend/generated/gql/graphql.ts, apps/web/frontend/mocks/accessTokenHandlers.ts, apps/web/frontend/mocks/mockServer.ts, apps/web/frontend/mocks/mocks.generated.ts, apps/web/pages/access-tokens.page.test.tsx, apps/web/pages/access-tokens.page.tsx, packages/backend/src/graphql/accessToken/accessToken.ts, packages/backend/src/graphql/accessToken/index.ts, packages/backend/src/graphql/accessToken/queries/accessTokensQueryField.test.ts, packages/backend/src/graphql/accessToken/queries/accessTokensQueryField.ts, packages/backend/src/graphql/accessToken/queries/index.ts, packages/backend/src/graphql/generated/schema.graphql, packages/backend/src/graphql/schema.ts, packages/backend/src/prisma/migrations/20240109151848_add_access_token_table/migration.sql, packages/backend/src/prisma/schema.prisma
=> feat: access token database table and a page

apps/web/frontend/components/inviteLink.tsx, packages/pulumi/index.ts, turbo.json
=> Added public NEXTAUTH_URL.

.env-sample, Dockerfile
=> fix: display app url in invite link

apps/web/frontend/components/projectMemberList/removeUserFromProjectButton.tsx
=> fix: delete icon for removing users from project

apps/web-e2e/src/pageObjects/projectsPage.ts, apps/web/frontend/components/addProjectMemberForm.tsx, apps/web/frontend/components/calendarSelector.tsx, apps/web/frontend/components/deleteTaskButton.tsx, apps/web/frontend/components/lockTaskButton.tsx, apps/web/frontend/components/projectMemberList/removeUserFromProjectButton.tsx, apps/web/frontend/components/reportForm/projectLockButton.tsx, apps/web/frontend/components/reportForm/reportForm.tsx, apps/web/frontend/components/taskList/taskList.spec.tsx, apps/web/frontend/components/taskList/taskList.tsx, apps/web/frontend/components/taskList/taskRow.tsx, apps/web/frontend/components/topNavigation/topNavigation.tsx, apps/web/frontend/components/trackingButtons/trackingButtons.tsx, apps/web/frontend/components/weekGrid/taskLockButton.tsx, apps/web/frontend/components/weekGrid/weekGridProjectRowGroup.tsx, apps/web/frontend/components/weekSelector.tsx, apps/web/frontend/generated/gql/gql.ts, apps/web/frontend/generated/gql/graphql.ts, apps/web/frontend/mocks/mocks.generated.ts, apps/web/pages/projects/index.page.tsx, packages/ui/package.json, packages/ui/src/listbox/listboxButton.tsx, packages/ui/src/listbox/listboxOption.tsx, pnpm-lock.yaml
=> draft: switches to button for task locking

apps/web/frontend/components/hourInput/hourInput.spec.tsx, apps/web/frontend/components/hourInput/hourInput.tsx
=> fix: hour input update

apps/web/frontend/components/taskList/taskRow.tsx
=> fix: tasks tab

apps/web/frontend/components/weekGrid/weekGridFooterRow.tsx, apps/web/frontend/components/weekGrid/weekGridProjectRowGroup.tsx, apps/web/frontend/components/weekGrid/weekGridTaskRow.tsx
=> fix: skeleton dimensions, placement

apps/web/frontend/components/weekGrid/weekGridDateHeaderRow.tsx
=> fix: week table header row adjustment

apps/web/frontend/components/weekGrid/weekGridProjectRowGroup.tsx
=> fix: doesn't include footer row in a tasks border

apps/web/frontend/components/weekGrid/weekGridDateHeaderRow.tsx
=> fix: week page table header width consistency

packages/backend/src/graphql/report/report.ts
closes: #871 
Co-authored-by: Pascal Helbig <PascalHelbig@users.noreply.github.com>
=> fix: optimizes prisma queries for report page

apps/web/frontend/components/trackingButtons/trackingButtons.tsx
=> feat: improves clarity of record buttons

apps/web-e2e/src/pageObjects/projectsPage.ts, apps/web/frontend/components/projectTable.tsx, apps/web/pages/projects/index.page.tsx
=> feat: projects page buttons design

apps/web/frontend/components/projectForm/deleteOrArchiveProjectButton/archiveProjectButton.tsx, apps/web/frontend/components/projectForm/projectForm.tsx
=> feat: changes design of buttons on project page

apps/web/frontend/components/calendarSelector.tsx, apps/web/frontend/components/timebookPage.tsx, apps/web/pages/_app.page.tsx
=> Week grid mobile view

.github/workflows/node.js.yml
=> chore: update digital ocean deploy action

apps/web/frontend/components/projectForm/projectForm.tsx
=> fix: prevent project members from changing the organization

apps/web/frontend/components/projectTable.tsx, apps/web/frontend/components/weekGrid/weekGridProjectRowGroup.tsx
=> feat: link to project details in week grid

packages/backend/src/paypalapi/paypalClient.ts
=> fix: fix for oauth token url

apps/web/frontend/components/reportForm/reportUserSelect.tsx, apps/web/frontend/components/reportForm/userLabel.tsx, apps/web/frontend/components/userLabel.tsx, apps/web/frontend/generated/gql/gql.ts, apps/web/frontend/generated/gql/graphql.ts, apps/web/frontend/mocks/mocks.generated.ts
=> feat: add list box image prop.

apps/web/frontend/components/projectForm/projectForm.tsx, apps/web/pages/access-tokens.page.tsx, package.json, packages/ui/src/table/table.tsx, pnpm-lock.yaml
=> updates prettier

.github/workflows/node.js.yml, apps/stream-deck/package.json, apps/web-e2e/package.json, apps/web/package.json, package.json, packages/backend/package.json, packages/eslint-config-custom/package.json, packages/ui/package.json, packages/validations/package.json, pnpm-lock.yaml
=> Compatibility issues with Typescript and ESLint

packages/backend/src/prisma/migrations/20250113135534_invoice_from_and_until_dates/migration.sql
=> fix: migration
